### ISSUE TITLE
memory corruption crash

### ISSUE THREAD

**Issue by maks** [InvisibleWrench/flutter_midi_command_linux#1]
@mortenboye  a big thank you again for adding Linux support, its mostly been working very well for me! Not only that, its served as a great example for doing other FFI integrations I'm working on with Dart.

I do say "mostly" just because I have run into a crash when sending largish sysex data. I'm sorry I haven't had a chance yet to try to reproduce the crash, but my suspicion at the moment is that it could be due to [this line](https://github.com/InvisibleWrench/flutter_midi_command_linux/blob/master/lib/flutter_midi_command_linux.dart#L368) as I think the `calloc` call should be passing in the size of the buffer as otherwise its only allocating a single `UInt8`, not an array of `UInt8`'s ? 

I think I didnt see this issue at first sending small mididata buffers with CC of only a few bytes, but I'm now trying to send [these sysex's](https://blog.segger.com/wp-content/uploads/2019/01/AkaiFireSysex.zip) which are from the [blog article on talking to a akai fire](https://blog.segger.com/decoding-the-akai-fire-part-3/) so I think the much bigger midi data buffers are now big enough to overwrite other parts of the heap and make `malloc` notice and crash.

**Comment by maks** [comment]
Seems that was the issue, with the 1-liner change in my PR I can now send large sysex messages over and over without crashing

**Comment by mortenboye** [comment]
You are indeed right, that the buffer size should be defined in alloc.

Thank you for your contribution. I have now updated the package.
