### ISSUE TITLE
cannot determine device number: Inappropriate ioctl for device

### ISSUE THREAD

**Issue by santoxyz** [InvisibleWrench/flutter_midi_command_linux#3]
I would like to use this plugin to connect to BleMIDI hardware under linux; but the example flutter app can't show any BT device, and in the console log I can see:

cannot determine device number: Inappropriate ioctl for device

If I connect the bleMIDI device using bluez,
I obtain the same output If I try on the linux terminal:
amidi -l
(as my laptop hasn't any MIDI hardware )

 BUT I can see the midi input and output ports exposed by it using
aconnect -l

I'm doing something wrong? Is there any workaround?

p.s.: I can correctly connect the midi service via alsa under Qt using https://github.com/waddlesplash/QMidi

**Comment by mortenboye** [comment]
This package does not currently supported MIDI over BLE on Linux. Sorry.
