### ISSUE TITLE
pure Dart version of this package?

### ISSUE THREAD

**Issue by maks** [InvisibleWrench/flutter_midi_command_linux#4]
My current project is Dart not Flutter based, so I need to have a pure dart package dependency for midi. 

I've recently taken over the abandoned `midi` package name on pub so I planned to publish the FFI Alsa midi bindings in this package under that name without the Flutter SDK dependency along with some sysex related code I've worked on for my project (with all due credit to your original work here of course).

I'd be happy to collaborate and try to make the new packages API suitable to be used by this package to avoid code duplication if it makes sense from your point of view to have this package depend on a pure-dart package?

I've also started a pure Dart Alsa binding package again following on from your great work here, so I also wonder if it would make sense to have a single dart package providing just the FFI Alsa binding part to be reused here?

**Comment by mortenboye** [comment]
Hi @maks thank you for your suggestion.

I haven't worked on any Dart projects without Flutter, so before I answer, can you help me understand what would be required to split the Dart part from the Flutter part. Is it simply a question of moving the two .dart files into a new package  and depend on those from here?

**Comment by maks** [comment]
@mortenboye thanks for the quick response and being open to the idea. 
Yes roughly I think that would be whats needed. The main thing is not to have dependencies on any Flutter SDK classes, which in this case I think all come in via `package:flutter_midi_command_platform_interface/flutter_midi_command_platform_interface.dart` 

I had a vague idea of possibly going one step further and have that package then depend on the `dart_alsa` package I created to pull in the ffigen auto generated binding file, but perhaps thats more trouble than its worth.

I'm also happy to transfer admin of the `midi` package on pub as well, if you would prefer to move it into your `invisiblewrench.com` publisher to have more confidence in depending on that package from this one.

**Comment by maks** [comment]
@mortenboye I started to have a quick go at doing this, but I quickly ran into the issue that `MidiDevice`, `MidiPort` and `MidiPacket` are all defined in `flutter_midi_command_platform_interface` which itself has a dependency on the Flutter SDK.

So I think my plan would be to create in the new  pure-dart package new methods for port init, connect, sendData etc depending only on the Alsa binding and then have this existing Flutter Linux plugin use those to implement its methods required by the `flutter_midi_command_platform_interface` class interface.

If you like, I can have a go at doing this (it may take me a little while) and submit a PR so you can see how it would look like and then consider if thats a good approach from your point of view?

**Comment by maks** [comment]
Sorry haven't had much time to work on this @mortenboye but I've now at least got an initial working version: https://github.com/maks/dart_midi able to receive and send midi messages with my test Akai Fire controller.

My next step is to refactor this plugin to make use of the package instead of alsa directly and then submit a PR here for you to have a look at.

**Comment by maks** [comment]
@mortenboye I finally got a chance to get the PR submitted, happy for any feedback you may have.

**Comment by maks** [comment]
One thing I'm not sure about is if I got the handling of the input/output ports working in a comparable manner.

**Comment by mortenboye** [comment]
hi @maks, thanks for your effort. I haven't had time to look into it and test it out yet, sorry.

**Comment by maks** [comment]
@mortenboye no worries at all. I've needed to pause working on the project I was using this for because I ran into issues with Dart not being able to pin threads for Isolates which seems to be needed in order to do low-latency audio playback.
